### ISSUE TITLE
problem for data

### ISSUE THREAD

**Issue by aooliver** [Sirui-Xu/STARS#3]
Hello, Sirui-Xu. 
The Link of "Human3.6m in exponential map can be downloaded from here."  which in STARS/deterministic/ cannot be opend, can you give a update one? 
Thanks you and Best wish.

**Comment by Sirui-Xu** [comment]
Hi, 

I can still use this link. Are there any network issues?

Best.

**Comment by OliverSTH** [comment]
Hi, @aooliver 
How do you solve this problem?
Can you tell me the solution?
Thank you.
