### ISSUE TITLE
Detail of 'cfg.nk' and 'stat' in 'diverse/main.py'

### ISSUE THREAD

**Issue by wangwenlonggg** [Sirui-Xu/STARS#4]
There have some questions about the correlation between 'nk' and ‘stat'：
’‘’
for i in range(cfg.nk):
        stat[i] = (indices == i).sum()
stat /= stat.sum()
‘’‘
what's the meaning of above code in 'diverse/main.py' lines 29~31?

**Comment by Sirui-Xu** [comment]
Hi @wangwenlonggg ,

Sorry for the delay. 'stat' refers to a metric utilized to evaluate the performance of anchors, determining which anchors are actively being used in the predictions (have the minimal error rate)

Best
